### ISSUE TITLE
Google-API Maps Sample

### ISSUE THREAD

**Issue by splatterb0y** [blackberry/BB10-WebWorks-Samples#100]
Hi @ctetreault do you know if it is possible to cache the Google Maps API? 
It's very slow to load and I haven't found a way to load it async. Can you help me?

**Comment by thtro** [comment]
I think caching is against their TOS...

**Comment by splatterb0y** [comment]
Its not about caching any search results, it's about caching their javascript loader and stuff OR atleast loading it async. If you add the google maps api to your webworks application the start-up time is recognizable increased, which annoys me.

**Comment by ctetreault** [comment]
I've never tried myself though I found a nice debate over here on the subject -- http://stackoverflow.com/questions/1965236/can-the-google-maps-api-javascript-be-cached

**Comment by splatterb0y** [comment]
This post was helping a bit. My solution is now to load GMaps API with jQuery.getScript and provide it with a callback that tells my application to hide the activity indicator and to continue.
