### ISSUE TITLE
view external pdf

### ISSUE THREAD

**Issue by hkao** [blackberry/BB10-WebWorks-Samples#102]
Hi,
Is there anyway to use invoke card or invoke to view external files such as pdf without having to download it?

I'm trying to use child web view, but when it encounters pdf files, it just shows blank.

Can one combine child web view with invoke card ?

Thanks!

**Comment by splatterb0y** [comment]
I am pretty sure you find the answer here (line 96 and following):
https://github.com/blackberry/BB10-WebWorks-Samples/blob/master/invoke/invoker/invocations.js#L96-L103

Dont know if the URI supports something like http:///<url> I guess you have to try it.

**Comment by timwindsor** [comment]
There shouldn't be a big issue with downloading a file temporarily to show in the the Adobe Reader. However, if you want a remote solution, you could try using pdf.js. It may be able to read in a remote URL for it's data and display the results in a webview.
