### ISSUE TITLE
FaceBook-OAuth-2 stops working with Error 500

### ISSUE THREAD

**Issue by asiayeah** [blackberry/BB10-WebWorks-Samples#113]
When the following is executed, "Error 500 The server is experiencing technical difficulties" is displayed instead of a Facebook login page:

var url = 'https://www.facebook.com/dialog/oauth?client_id=' + facebookOptions.clientId + '&redirect_uri=' + facebookOptions.redirectUri + '&scope=publish_stream,read_stream';
childWindow = window.open(url, '_blank');

It used to work. I am now testing in BlackBerry 10 Dev Alpha Simulator BB10_0_10.261.

I am not sure if it's a temporary glitch at Facebook or they have changed something that it no longer likes the HTTP request sent from BB10 to it. I have tried to invoke the same URL in the BB10 browser with the same 500 error.

**Comment by timwindsor** [comment]
@ctetreault Can you take a look, Chad?

**Comment by asiayeah** [comment]
I still got the Error 500 as of now. To reproduce, one should uninstall the app, install it again and then login.

That means the initial login always fail with 500. For testing purposes, if I changed the above url to "http://www.facebook.com", it will allow me to login within my WebWorks app. Then I revert the ur, reinstall the app and it will work! However, once I uninstall the app and install it again. It stops working.

It maybe related to some missing cookies, which shouldn't be...

@ctetreault Please kindly comment. Let me know if you need more details.

**Comment by asiayeah** [comment]
I found the issue is not BB10 specific. I can reproduce it on any desktop browser.
1. Remove all facebook.com cookies
2. Launch the  'https://www.facebook.com/dialog/oauth?client_id=... will get Error 500.

Here's a bug report on facebook related to this one: https://developers.facebook.com/bugs/491147611024519?browse=search_51547aefcf1d29084346605

**Comment by asiayeah** [comment]
Facebook has acknowledged and fixed the issue on their side. I am closing this one. Thanks.

**Comment by timwindsor** [comment]
Thanks very much for tracking this down!
