### ISSUE TITLE
pimcalendar example not working with bbui-0.9.6

### ISSUE THREAD

**Issue by thristov** [blackberry/BB10-WebWorks-Samples#147]
WebWorks example "pimcalendar" is not working properly after changing bbui to version 0.9.6, option Find Events. After entering any search info and pressing button Search nothing really happens, the app stays on the same screen (findEvents), findResult screen is never displayed. When pressing the Back button there is an empty findEvents screen.

**Comment by timwindsor** [comment]
@oros Can you take a look at this issue? This example should be updated to 0.9.6 anyway.

**Comment by oros** [comment]
@thristov There are some new BBUI requirements when a Context Menu is being used. Sample has been updated and will be contributed back upstream momentarily.

Specifically: An extension must be included and config.xml must be updated.

For reference:
https://github.com/blackberry/bbUI.js/wiki/Context-Menus

**Comment by thristov** [comment]
Thanks! Working like a champ! Closing issue.
