### ISSUE TITLE
Regarding downloading an image using FileTransfer

### ISSUE THREAD

**Issue by bbsam** [blackberry/BB10-WebWorks-Samples#150]
Hi,

I am trying to download an image from an URL to the shared path on the device using FileTransfer. This results in Error code 4 "Permission error'. As per the API documentation it is not required to specify any permission but not understanding what kind of permission it is asking for. Please find the code below.

I have added the filetransfer feature in config.xml.

```
    try {
        blackberry.io.filetransfer.download(
            obj.results.resultsList.item[0].images.image,
            blackberry.io.sharedFolder + "/downloads/1.jpg",
            function (result) {
                alert("Download successful");
                alert("fullPath: " + result.fullPath);
            },
            function (result) {
                alert("Download failed");
                alert("Error code: " + result.code);
                alert("HTTP status: " + result.http_status);
                alert("Source: " + result.source);
                alert("Target: " + result.target);
            });
    }
    catch(e) {
        alert("Exception in download: " + e);
    }
```

Please provide some help to achieve this.

Thanks in advance.

**Comment by timwindsor** [comment]
Did you include the permission as shown in the app's config.xml?

https://github.com/blackberry/BB10-WebWorks-Samples/blob/master/fileTransfer/app/config.xml#L46-L48

**Comment by bbsam** [comment]
Hi Tim,

Yes, I do have included the access_shared permissions in my config.xml.

**Comment by jeffheifetz** [comment]
@haahmad any ideas?

**Comment by haahmad** [comment]
@jeffheifetz @bbsam I don't know if you are using the HTML5 filesystem API, but if you are you need to set `blackberry.io.sandbox` to false to use the shared folder. 
https://developer.blackberry.com/html5/apis/blackberry.io.html#.sandbox

**Comment by bbsam** [comment]
I am using this API to download the images

https://developer.blackberry.com/html5/apis/blackberry.io.filetransfer.html

**Comment by bbsam** [comment]
Hi,

I have followed this and found a solution

https://github.com/blackberry/BB10-WebWorks-Framework/issues/382

Thanks.

**Comment by gcsantiago** [comment]
@bbsam Hi, what was exactly the solution you found there? Thanks
