### ISSUE TITLE
Error in bfb_bootstrap.js when I try the Built-For-BlackBerry Sample

### ISSUE THREAD

**Issue by 0xLuz** [blackberry/BB10-WebWorks-Samples#154]
Well, I have started  with WebWorks in the lasts days and I'm learning how to use the bbUI.js . In trying make a screen transition with bb.pushScreen() and it doesn't work, I've this error:

https://dl.dropboxusercontent.com/u/85402777/screen5.png

When I click in the arrow that is a button for another screen this error is shown, well, I can't find the problem. Can someone help me, please?

To call the new screen I'm using:

<pre> onclick="bb.pushScreen('secondScreen.html', 'secondScreen');" </pre>

In the arrow div

**Comment by timwindsor** [comment]
Did you resolve this?

**Comment by 0xLuz** [comment]
Yes! bbUI.js bbUI.css were of the old version, I downloaded the lastest version here https://github.com/blackberry/bbUI.js and I changed the old files. I think that `Built-For-BlackBerry` Sample need to be updated and the css too.
