### ISSUE TITLE
Out of date sample: OLD BFB Sample

### ISSUE THREAD

**Issue by ctetreault** [blackberry/BB10-WebWorks-Samples#165]
Now that we've published the new boilerplates, can we deprecate the old one here? https://github.com/blackberry/BB10-WebWorks-Samples/tree/master/Built-For-BlackBerry

**Comment by kwallis** [comment]
Sounds good to me. Update the Readme, perhaps tag the repo, then remove?

**Comment by timwindsor** [comment]
We haven't done much tagging at all on the sample repos, so we don't really have a strategy in place. How would you  like to see it tagged?

**Comment by ctetreault** [comment]
"Defunct"

Sent from my BlackBerry 10 smartphone.
From: Tim Windsor
Sent: Tuesday, October 15, 2013 5:08 PM
To: blackberry/BB10-WebWorks-Samples
Reply To: blackberry/BB10-WebWorks-Samples
Cc: Chad Tetreault
Subject: Re: [BB10-WebWorks-Samples] Out of date sample: OLD BFB Sample (#165)

We haven't done much tagging at all on the sample repos, so we don't really have a strategy in place. How would you like to see it tagged?

—

## Reply to this email directly or view it on GitHubhttps://github.com/blackberry/BB10-WebWorks-Samples/issues/165#issuecomment-26372328.

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by kwallis** [comment]
I believe tags are usually used to potentially go back in time and relates
to the entire repo, so in a sense you want to go back to something
"positive". Also something more descriptive? Maybe just "BfB deprecation"?

**Comment by timwindsor** [comment]
All right, I'll do that today.
