### ISSUE TITLE
FaceBook OAuth 2.0

### ISSUE THREAD

**Issue by NadyaD** [blackberry/BB10-WebWorks-Samples#21]
I followed the instructions and set up the redirect script on my server. I am able to go past successfully  requesting a token, but when i am redirected to the facebook login screen I get a popup window which says: "Access to "http://facebook.techadvantage.ca/redirect.php?code=AQBHnO3CJpOo...._=_" not allowed "

**Comment by NadyaD** [comment]
added <access uri="my website url" subdomains="true" /> to config.xml and it fixed the error

**Comment by astanley** [comment]
Thanks NadyaD - just to confirm was that just an oversight, or did we miss including that step in the Oauth-Facebook README?

**Comment by NadyaD** [comment]
It would be helpful to add that to the instructions, however for those familiar with playbook app development this information is explained in playbook app setup. But in this sample, I think it needs to be mentioned that 
<access uri="http://oauth.chadtatro.com" subdomains="true" /> in config.xml
should be changed to your website's domain.

**Comment by astanley** [comment]
- @ctetreault for visibility.  Feedback about your sample.
