### ISSUE TITLE
Cordova Notification not work

### ISSUE THREAD

**Issue by MXZZ** [blackberry/BB10-WebWorks-Samples#220]
the examples  Notify not work correctly and it not create the notification on BlackBerry Hub.
https://github.com/blackberry/BB10-WebWorks-Samples/tree/master/notify

My application i tried to convert from webworks 1.0 to webworks 2.0 also have this issue.
Please help!

**Comment by timwindsor** [comment]
Okay, please check with the latest changes - they were just a rename of some of the index.htm files to index.html. It's likely that the default app was not launching properly due to that.

**Comment by MXZZ** [comment]
No! Reverse the changes please because now the Notify sample doesn't start (not without complementary renaming of "index.htm in index.html"  in config.xml).
The previous version of sample Notify stars correcly but when pressing any button it does nothing  : No notifications sent on BlackBerry Hub like  Webworks 1.0 version ( onError: callback is always called instead )
The new modified version  ever with the renaming of index.htm have the same issue.
I think that the cordova package com.blackberry.notification is broken or  the permission "post_notification" is not granted correcly ever if listed in config.xml 

Sorry for troubles and Thank you for your time 
Marco

**Comment by timwindsor** [comment]
I have investigated this issue in more detail. There were several issues, and I don't think it was ever tested beyond seeing the notification in the inbox. Sorry about that.

I've fixed what I could, but some of the sample functions are assuming data that is not coming from the invocation. I opened an issue internally to see about them: BRWSR-16362

Let me know how this works for you.

**Comment by MXZZ** [comment]
Yes, it works for me :) 

Thank you, you're the best!
Marco Gallo

**Comment by timwindsor** [comment]
Awesome - glad to know that we could help.
