### ISSUE TITLE
Sorry, but how to test it on my device?

### ISSUE THREAD

**Issue by newpen** [blackberry/BB10-WebWorks-Samples#239]
I followed the instructions to build the WebWorksWeather. It's installed on my Z30. Once I open it, the splash screen is showing ok, but then it went to a blank black screen, and nothing else is showing. What am I missing here?

**Comment by timwindsor** [comment]
There's an issue with the use of an older API that I see in it, which I've explained in more detail in issue #240. You can comment out the lines 151-166 in init.js to make it work for now.

I should also mention you can use WebInspector to debug issues like this. You will find it invaluable as you develop your own apps: https://developer.blackberry.com/html5/documentation/v2_2/debugging_using_web_inspector.html
