### ISSUE TITLE
unable to get access token from Facebook using FaceBook-OAuth-2 in BB10

### ISSUE THREAD

**Issue by mushtaq34** [blackberry/BB10-WebWorks-Samples#36]
Hi,
    I'm trying to get access token from Facebook, with following the procedure mentioned in FaceBook-OAuth-2. Getting 'authcode' successfully after that unable to perform Ajax with following url,
'https://graph.facebook.com/oauth/access_token?client_id=' + facebookOptions.clientId + '&redirect_uri=' + facebookOptions.redirectUri + '&client_secret=' + facebookOptions.clientSecret + '&code=' + authCode'.  

Getting Error getting access_token: alert.(calling Ajax Error function).

**Comment by timwindsor** [comment]
@ctetreault can you help out with this issue?

**Comment by mushtaq34** [comment]
Hello Tim Windsor,
     Thank you for your response. I am happy to help you.

**Comment by ctetreault** [comment]
I would start by checking with Web Inspector to see a)  what is being sent to facebook from the app, and b)  what exactly is facebook sending back?  there should be some descriptive error message on their end as to what the issue is.

**Comment by mushtaq34** [comment]
I am getting alert message like 'Error getting access_token: '. If I tried to do using top.location.replace instead of Ajax request then getting Access token successfully in a blank screen. But it will not redirect to local:///index.html as per redirect.php.

**Comment by mushtaq34** [comment]
I got the exact error by checking with Web Inspector..

Error getting access_token: {
   "error": {
      "message": "Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request",
      "type": "OAuthException",
      "code": 100
   }
}

**Comment by mushtaq34** [comment]
Hi All,
    I found the mistake in my implementation. I initialized the 'facebookOptions' variable when user clicking on the Facebook login button in my App. If I am assigning this into the loadWebWorks() function it's working properly. 

The function is,
function loadWebWorks() {
    document.addEventListener("webworksready", initApp());
}

function initApp(){
    // facebook oauth setup
    facebookOptions = {
        clientId: FBappID,
        clientSecret: FBappSecret,
        // we use a php script on a server because facebook doesn't allow for local:/// callbacks
        // at this time.  the php simply redirects us back to 'local:///index.html'
        redirectUri: serverURL
    };
}

**Comment by gcsantiago** [comment]
@mushtaq34 you say "// we use a php script on a server because facebook doesn't allow for local:/// callbacks
// at this time. the php simply redirects us back to 'local:///index.html' "

in my experience this is not exactly... im using the FB object, without php, and works like a charm in Ripple, but the matter is bb10dev Alpha dont send any domain then FB refuse it, the app need to send some domain at least localhost... i prefer the FB object for security reason and for the practicity of their use... i dont know why no one has been interested :/ 

Regards

http://developers.facebook.com/docs/reference/javascript/
