### ISSUE TITLE
pimcalendar invoke

### ISSUE THREAD

**Issue by gcsantiago** [blackberry/BB10-WebWorks-Samples#49]
Im using pimcalendar on bb10 and successful create an event and get their id, then, how can i invoke the calendar with this id to open the event? Thx

**Comment by gcsantiago** [comment]
@ctetreault Chad Do you know if it possible to invoke a target event in the calendar mention their ID ? Thanks

**Comment by astanley** [comment]
Very sorry for the delayed reply.  Yes you can invoke a specific event in the calendar.  More info here: https://developer.blackberry.com/html5/documentation/calendar.html

**Comment by gcsantiago** [comment]
Thanks Adam ! I will try.
