### ISSUE TITLE
navigator.geolocation.getCurrentPosition is not triggering either callbacks

### ISSUE THREAD

**Issue by Quackerjack** [blackberry/BB10-WebWorks-Samples#58]
Some of us are having problems with the navigator.geolocation.getCurrentPosition in Webworks for BB10 Gold Edition as it does not trigger either the success or fail callbacks. Please also read this as other developer are encountering the same issues:
http://supportforums.blackberry.com/t5/Web-and-WebWorks-Development/Geolocation-always-times-out/td-p/2020591/highlight/true

Here is the code I'm using that never triggers either callbacks:

```
    var gpsOptions = {enableHighAccuracy:true, timeout: 1000, maximumAge:300000}

    if(navigator.geolocation!==null){
        if(debug==true) console.log("GPS API found. Getting GPS coordinates");
        navigator.geolocation.getCurrentPosition(myGPS.updateGPSCallbackSuccess, myGPS.updateGPSCallbackFailed, gpsOptions); // CODE NEVER EXECUTES EITHER SUCCESS OR FAIL CALLBACKS!
            }
```

**Comment by astanley** [comment]
Was this issue closed on purpose?

Here is a functional example of using geolocation on BlacKBerry 10.  Is this not working as expected on your device?

https://github.com/blackberry/BB10-WebWorks-Samples/tree/master/Maps

**Comment by Quackerjack** [comment]
It works fine in Ripple, but will not work in Dev Alpha (latest build).

I moved issue to Webworks instead of Samples.

**Comment by rodnolan** [comment]
https://github.com/blackberry/BB10-WebWorks-Framework/issues/487... for the benefit of future googlers
