### ISSUE TITLE
FaceBook-OAuth-2 stop working after upgraded to WebWorks SDK 1.0.4.5 (Gold SDK)

### ISSUE THREAD

**Issue by asiayeah** [blackberry/BB10-WebWorks-Samples#59]
Previous technique to redirecting to local:///index.html doesn't work with the new SDK:

From Web Inspector, we got an error message:
Not allowed to load local resource: local:///index.html

Is it still possible with the Gold SDK? 

The following whitelisting doesn't seem to fix it:

```
<access uri="local://" subdomains="true" />
```

**Comment by timwindsor** [comment]
@ctetreault have you seen this on the new SDK?

**Comment by ctetreault** [comment]
oh boy..  I'll test it out tomorrow, I think I _may_ know what's going on.

**Comment by asiayeah** [comment]
Any luck?
Sent from my BlackBerry® smartphone

-----Original Message-----

**Comment by ctetreault** [comment]
Still investigating.  Will report back as soon as I can

**Comment by asiayeah** [comment]
Happy New Year! Could we get this sorted out quickly to have a good start on 2013?

**Comment by ctetreault** [comment]
After talking with the WebWorks team, and doing some more testing, it looks like the sames will work as is, BUT you must now specifically whitelist the Facebook/Twitter callback URL's in your config.xml.  

I have updated the samples to show this, please refer to them for more detailed info ;)

**Comment by asiayeah** [comment]
Thank you! That solves my issue, too.

**Comment by timwindsor** [comment]
So can this issue be closed?

**Comment by ctetreault** [comment]
I believe so, yes
