### ISSUE TITLE
Invoker app in Invoke Sample has a broken option "Open a JPG"

### ISSUE THREAD

**Issue by jeffheifetz** [blackberry/BB10-WebWorks-Samples#8]
What he ^ said

**Comment by nukulb** [comment]
@haahmad - thoughts on this?

can you have a quick look please?

**Comment by haahmad** [comment]
I just fired up the application in webinspector, its broken because my XHR calls have been deprecated, I will fix it.

**Comment by haahmad** [comment]
I'm getting a 403 error when trying to push by branch with the fix...
