### ISSUE TITLE
WindowCovers Sample presents white screen

### ISSUE THREAD

**Issue by ssshake** [blackberry/BB10-WebWorks-Samples#85]
Hi, I'm trying to use the windowcovers sample but it doesn't appear to be working. I get a white screen, not like the screenshots. I have a feeling I'm missing something fundamental. Should I be able to clone this git repo, build WindowsCovers and deploy without any modification?

I see there are three html files, index, app and setLabel, but a quite look through the code I don't see where app or set get called. Also body is empty. 

Advice please? I'm looking to get this working for my app. Thanks.

**Comment by timwindsor** [comment]
Are you building with the latest SDK, on the latest OS?

The App.js file does all the real application logic and pushes the app.html and setLabel.html files to the screen:
https://github.com/blackberry/BB10-WebWorks-Samples/blob/master/WindowCovers/js/app.js

**Comment by ssshake** [comment]
User error. I got it working just a few minutes ago. Thanks. 
-----Original Message-----

**Comment by timwindsor** [comment]
Excellent! Glad to hear it.

**Comment by ssshake** [comment]
Not to take advantage of this email but do you know if covers can reference urls for its image? I'm trying to do this but since its not working I'm thinking I need to get and save the image first and then reference it locally
-----Original Message-----

**Comment by timwindsor** [comment]
That was our first request too, and it's not integrated quite yet, but a community member submitted code for it. You can probably safely use it as it's been reviewed just waiting on some test cases to be added before it goes in. It's in this pull request: https://github.com/blackberry/BB10-WebWorks-Framework/pull/501

**Comment by ssshake** [comment]
Thanks I assume you're talking about this file:
https://github.com/jcarty/BB10-WebWorks-Framework/blob/318de5df863928514bd778f304cf3f2c11fd98c9/ext/ui.cover/client.js

I would love to use their code but I have no idea how to go about that.

**Comment by timwindsor** [comment]
It's actually pretty easy in this case.

download that file (you can use the Raw option in Github and save it over top of your BB10SDK/Framework/ext/ui.cover/client.js file that is there now (probably want to back up the one that's there just in case).

Then you've got to change one line that is incorrect:
https://github.com/jcarty/BB10-WebWorks-Framework/blob/318de5df863928514bd778f304cf3f2c11fd98c9/ext/ui.cover/client.js#L29

Should use "webkitRequestFileSystem" instead of "requestFileSystem"

And you should be good.

**Comment by ssshake** [comment]
Oh ha that is pretty simple. Thought I'd have to build it as per the build instructions on github. Thanks ill try it out soon!
-----Original Message-----

**Comment by ssshake** [comment]
Call you tell me how I can find out the usage for this?

Is it simply blackberry.cover.setContent(blackberry.ui.cover.TYPE_URI, {
path: "https://domain.com/image"
});

**Comment by timwindsor** [comment]
Looks like he changed the parameter from "path" to "uri". It's described here in the file:
https://github.com/jcarty/BB10-WebWorks-Framework/blob/318de5df863928514bd778f304cf3f2c11fd98c9/ext/ui.cover/client.js#L70

**Comment by ssshake** [comment]
Doesnt seem to be working. Please review my code if you dont mind. Doe the
TYPE_URI spot look right?

// setup the cover
function updateCover() {

```
// set cover photo
blackberry.ui.cover.setContent(blackberry.ui.cover.TYPE_URI, {
    uri: "http://www.google.ca/images/srpr/logo3w.png"
});

// set cover label
blackberry.ui.cover.labels.push({
    label: "Porch Camera",
    size: 10,
    wrap: true
});

// update the cover
blackberry.ui.cover.updateCover();
```

 // minimize the app
    setTimeout(function(){
        blackberry.app.minimize();
    }, 1000);
}

---

Here are the changes made to client.js. How can I verify that this new .js
file got bundled into the project? Is that automatic?

_self.saveUri = function (blob, onComplete, onError) {
    window.webkitrequestFileSystem(window.TEMPORARY, 1024 \* 1024, function
(fs) {
        fs.root.getFile("cover.png", {create: true}, function (fileEntry) {
            fileEntry.createWriter(function (fileWriter) {
                cover.cover.path = fileEntry.file.fullPath;
                fileWriter.onwriteend = onComplete;
                fileWriter.write(blob);
            }, onError);
        }, onError);
    }, onError);
};

**Comment by timwindsor** [comment]
Ah, you seem to be trying to use this to download and use a remote image. The code that I sent you is for using Data URI's. That's my fault - I misread your initial question. 

You can probably just download the file and then use it with the standard image option. Use the FileTransfer api to download the file to a local path, then pass that path to the Cover API when you get a success callback:
https://developer.blackberry.com/html5/apis/blackberry.io.filetransfer.html#.download

**Comment by ssshake** [comment]
Well considering I didnt know what a data-uri was I'd say part of the blame
is on my end.

My original approach was in fact what you just described. I had been
messing with the filetransfer sample from git and the performance seemed to
be not very good. I'm going to mess around with that for a bit more and see
what's up. The default sample uses a pdf, when I tried to change it to img
it didnt work. I probably need to do my homework here. Thanks.

**Comment by ghost** [comment]
Actually, I've been having odd issues with the FileTransfer sample myself. My PHP server never seems to receive the name or content type EVER, only other params I may add to the request.

Might need a Dev Alpha or actual device to test. Too many unknowns or unimplemented functions in the simulator, and inconsistent results in Ripple.

## 

James Robert Perih
james.perih@nerdsonsite.com
Cell: 204.688.6211
Nerds On Site
www.nerdsonsite.com

Sent from my Windows Phone on the Telus Mobility Network

**Comment by ssshake** [comment]
Sad to hear. Luckily for me I got this working properly. Downloads an
image, displays it with cover window. Need to figure out how to get this
image to refresh every few seconds as the app I'm writing monitors my
security cameras.

Thanks for the help on this thread. I agree that ripple isn't as great as
it could be. Unless I'm just not aware it doesnt give me a good way to
debug for device conditions prior to deploying. When in ripple I most often
just have a blank screen, which is odd because some of the time things do
display decently in firefox. BBUI.js sample for example.

I encourage the development support to whip up more examples
