### ISSUE TITLE
Foursquare invoke card error

### ISSUE THREAD

**Issue by gcsantiago** [blackberry/BB10-WebWorks-Samples#98]
Hi, may be @ctetreault Chad can figure out why I receive this in place of login and authorization... Im using the new invocation card from the new example (and isn't send any callback uri there) (and the uri on the foursquare app page is correct and working with REST)...

may be another limitation of my Dev Alpha A ?

![IMG_00000186](https://f.cloud.github.com/assets/1733575/155029/5623db9e-7634-11e2-976f-8e25415b5052.png)

**Comment by ctetreault** [comment]
Ahh yes.. I forgot to add some info to the docs.

You need to set your applications callback (on developer.foursqaure.com) to "http://localhost"

**Comment by gcsantiago** [comment]
Thanks Chad... I'll see...

**Comment by timwindsor** [comment]
Did this work for you @gcsantiago?

**Comment by gcsantiago** [comment]
Sorry, can't test it, I'm still with the previous window.open login way, but I believe in Chad and no one put an additional comment, so I suggest to close it for now. Thanks

**Comment by ctetreault** [comment]
I think we're safe to close this issue now. :)
